# Generated by Django 5.0.5 on 2024-05-11 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billproductitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='billserviceitem',
            name='pet',
        ),
        migrations.RemoveField(
            model_name='billserviceitem',
            name='service',
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.DeleteModel(
            name='BillProductItem',
        ),
        migrations.DeleteModel(
            name='BillServiceItem',
        ),
    ]
