# Generated by Django 5.0.5 on 2024-05-11 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0005_initial'),
        ('services', '0002_alter_serviceprice_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='billproductitem',
            name='bill',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product_to_bill', to='services.service'),
        ),
        migrations.AddField(
            model_name='billserviceitem',
            name='bill',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='service_to_bill', to='services.service'),
        ),
    ]
