# Generated by Django 5.0.5 on 2024-05-11 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0007_alter_billproductitem_bill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billserviceitem',
            name='bill',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_to_bill', to='bills.bill'),
        ),
    ]
