# Generated by Django 5.0.5 on 2024-05-11 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0008_alter_billserviceitem_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billproductitem',
            name='bill',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_to_bill', to='bills.bill'),
        ),
    ]
