# Generated by Django 5.0.5 on 2024-05-11 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0011_alter_billproductitem_bill_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='data_paid',
            new_name='date_paid',
        ),
        migrations.AlterField(
            model_name='billproductitem',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_items', to='bills.bill'),
        ),
        migrations.AlterField(
            model_name='billserviceitem',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_items', to='bills.bill'),
        ),
    ]
