# Generated by Django 5.0.5 on 2024-05-26 17:00

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, default='global/no-image.jpg', null=True, upload_to=products.models.get_image_path),
        ),
    ]
