# Generated by Django 5.0.5 on 2024-05-26 04:01

import django.db.models.deletion
import pets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_range', models.CharField(max_length=255)),
                ('weight_type', models.CharField(max_length=50)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='species_weight', to='pets.species')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.BooleanField(default=0)),
                ('photo', models.ImageField(blank=True, default='global/no-image.jpg', null=True, upload_to=pets.models.get_image_path)),
                ('owner', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets_owner', to='customers.customer')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='belong_species', to='pets.species')),
                ('weight', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='have_weight', to='pets.weight')),
            ],
        ),
    ]
