# Generated by Django 5.0.5 on 2024-05-31 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
        ('services', '0002_delete_servicesurchanges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Weight',
        ),
    ]
