# Generated by Django 5.0.5 on 2024-05-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight',
            name='weight_type',
            field=models.CharField(default='small', max_length=50),
        ),
    ]
