# Generated by Django 5.0.5 on 2024-05-31 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_pet_weight_delete_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
