# Generated by Django 5.0.5 on 2024-05-11 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_alter_weight_weight_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weight_species', to='pets.species'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='belong_species', to='pets.species'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='weight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='have_weight', to='pets.weight'),
        ),
    ]
