# Generated by Django 5.0.5 on 2024-05-11 06:23

import pets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_weight_species_alter_pet_species_alter_pet_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='photo',
            field=models.ImageField(blank=True, default='global/no-image.jpg', null=True, upload_to=pets.models.get_image_path),
        ),
    ]
