# Generated by Django 5.0.5 on 2024-05-15 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_photo_alter_customer_address'),
        ('pets', '0005_pet_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets', to='customers.customer'),
        ),
    ]
