# Generated by Django 5.0.5 on 2024-05-21 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_alter_pet_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='year_of_birth',
            new_name='age',
        ),
        migrations.RemoveField(
            model_name='weight',
            name='species',
        ),
    ]
