# Generated by Django 5.0.5 on 2024-05-10 05:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='for_species', to='pets.species')),
            ],
        ),
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('price', models.FloatField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belong_services', to='services.service')),
                ('weight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_weight', to='services.service')),
            ],
        ),
    ]
