# Generated by Django 5.0.5 on 2024-05-11 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_pet_photo'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprice',
            name='weight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_weight', to='pets.weight'),
        ),
    ]
