# Generated by Django 5.0.5 on 2024-05-31 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceSurchanges',
        ),
    ]
