# Generated by Django 5.0.5 on 2024-05-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_serviceprice_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='ServicePrice',
        ),
    ]
