# Generated by Django 5.0.5 on 2024-05-31 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_delete_servicesurchanges'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_one_day',
            field=models.BooleanField(default=True),
        ),
    ]
