# Generated by Django 5.0.5 on 2024-05-21 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_rename_year_of_birth_pet_age_remove_weight_species'),
        ('services', '0003_service_price_delete_serviceprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSurchanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surchange', models.FloatField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surchange_service', to='services.service')),
                ('weight', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surchange_weight', to='pets.weight')),
            ],
        ),
    ]
