# Generated by Django 5.0.5 on 2024-05-26 04:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        ('employees', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBill',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('received', models.FloatField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='create_product_bill', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ProductBillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_item', to='bill.productbill')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_item', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceBill',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('received', models.FloatField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_bill', to='booking.servicebooking')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='create_booking_bill', to='employees.employee')),
            ],
        ),
    ]
