# Generated by Django 5.0.5 on 2024-05-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbill',
            name='payment_method',
            field=models.CharField(choices=[('on', 'online'), ('off', 'offline')], default='on', max_length=20),
        ),
    ]
