# Generated by Django 5.0.5 on 2024-05-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_productbill_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebill',
            name='payment_method',
            field=models.CharField(choices=[('on', 'online'), ('off', 'offline')], default='on', max_length=20),
        ),
    ]
