# Generated by Django 5.0.5 on 2024-05-28 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_servicebill_payment_method'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbill',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='buy', to='customers.customer'),
        ),
    ]
