# Generated by Django 5.0.5 on 2024-05-28 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0004_productbill_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbill',
            name='received',
        ),
        migrations.RemoveField(
            model_name='servicebill',
            name='received',
        ),
    ]
