# Generated by Django 5.0.5 on 2024-06-10 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0006_surcharge'),
        ('products', '0003_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbillitem',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_item', to='bill.productbill'),
        ),
        migrations.AlterField(
            model_name='productbillitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_item', to='products.product'),
        ),
    ]
