# Generated by Django 5.0.5 on 2024-05-26 04:01

import booking.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('employees', '0001_initial'),
        ('pets', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('is_booked', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('date_booked', models.DateField(blank=True, default='2024-05-26')),
                ('date_start', models.DateField()),
                ('stay_days', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('c', 'completed'), ('a', 'accept'), ('p', 'proceed'), ('u', 'unacept')], default='u', max_length=50)),
                ('photo', models.ImageField(blank=True, default='global/no-image.jpg', null=True, upload_to=booking.models.get_image_path)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_booked', to='customers.customer')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pet_booked', to='pets.pet')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_booked', to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='PetCheckInOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_checked_in', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('date_checked_out', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_picked_up', models.BooleanField(blank=True, default=False)),
                ('emp_checked_in', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_checkin_pet', to='employees.employee')),
                ('emp_checked_out', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_checkout_pet', to='employees.employee')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_check_inout', to='booking.servicebooking')),
            ],
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_diary', to='employees.employee')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_diary', to='booking.servicebooking')),
            ],
        ),
        migrations.CreateModel(
            name='SubService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('c', 'completed'), ('a', 'accept'), ('p', 'proceed'), ('u', 'unacept')], default='u', max_length=50)),
                ('photo', models.ImageField(blank=True, default='global/no-image.jpg', null=True, upload_to=booking.models.get_main_image_path)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_service_booked', to='services.service')),
                ('service_booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_booking', to='booking.servicebooking')),
            ],
        ),
    ]
