# Generated by Django 5.0.5 on 2024-05-31 03:20

import booking.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebooking',
            name='photo',
        ),
        migrations.AddField(
            model_name='diary',
            name='photo',
            field=models.ImageField(blank=True, default='global/no-image.jpg', null=True, upload_to=booking.models.get_main_image_path),
        ),
        migrations.AddField(
            model_name='petcheckinout',
            name='room',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booked_room', to='booking.room'),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='date_booked',
            field=models.DateField(blank=True, default='2024-05-31'),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='status',
            field=models.CharField(choices=[('e', 'cancel'), ('c', 'completed'), ('a', 'accept'), ('p', 'proceed'), ('u', 'unacept')], default='u', max_length=50),
        ),
        migrations.DeleteModel(
            name='SubService',
        ),
    ]
