# Generated by Django 5.0.5 on 2024-05-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_booked',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
