# Generated by Django 5.0.5 on 2024-05-21 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_room_is_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 21, 8, 13, 19, 710576)),
        ),
    ]
