# Generated by Django 5.0.5 on 2024-05-31 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_rename_number_room_name'),
        ('services', '0003_service_is_one_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='room_booked', to='booking.room'),
        ),
        migrations.CreateModel(
            name='SubServiceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_subservices', to='booking.servicebooking')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subservice_booked', to='services.service')),
            ],
        ),
        migrations.DeleteModel(
            name='PetCheckInOut',
        ),
    ]
