# Generated by Django 5.0.5 on 2024-05-21 08:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_diary_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 21, 8, 14, 17, 751151, tzinfo=datetime.timezone.utc)),
        ),
    ]
