# Generated by Django 5.0.5 on 2024-05-31 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_servicebooking_room_subservicebooking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='note',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
