# Generated by Django 5.0.5 on 2024-05-21 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_diary_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
