# Generated by Django 5.0.5 on 2024-05-21 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_diary_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petcheckinout',
            name='date_checked_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='petcheckinout',
            name='date_checked_out',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
