# Generated by Django 5.0.5 on 2024-05-31 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_servicebooking_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='subservicebooking',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
