# Generated by Django 5.0.5 on 2024-06-01 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_subservicebooking_is_completed'),
        ('services', '0003_service_is_one_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='date_booked',
            field=models.DateField(blank=True, default='2024-06-01'),
        ),
        migrations.AlterField(
            model_name='subservicebooking',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_subservices', to='booking.servicebooking'),
        ),
        migrations.AlterField(
            model_name='subservicebooking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subservice_booked', to='services.service'),
        ),
    ]
