# Generated by Django 5.0.5 on 2024-06-10 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_servicebooking_date_booked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_diary', to='booking.servicebooking'),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='date_booked',
            field=models.DateField(blank=True, default='2024-06-10'),
        ),
    ]
