# Generated by Django 5.0.5 on 2024-06-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_diary_booking_alter_servicebooking_date_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='date_booked',
            field=models.DateField(blank=True, default='2024-06-14'),
        ),
    ]
