# Generated by Django 5.0.5 on 2024-05-26 04:00

import django.db.models.deletion
import employees.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=50)),
                ('date_of_joining', models.DateField(blank=True, default='2024-05-26', null=True)),
                ('status', models.CharField(choices=[('w', 'working'), ('q', 'quit'), ('l', 'leave')], default='w', max_length=50)),
                ('role', models.CharField(choices=[('m', 'manager'), ('e', 'employee'), ('s', 'security')], default='e', max_length=50)),
                ('photo', models.ImageField(blank=True, default='global/no-image.jpg', null=True, upload_to=employees.models.get_image_path)),
                ('account', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, default=None, null=True)),
                ('end_time', models.TimeField(blank=True, default=None, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allot', to='employees.employee')),
            ],
        ),
    ]
