# Generated by Django 5.0.5 on 2024-05-10 06:29

import employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, default='global/no-image.jpg', null=True, upload_to=employees.models.get_image_path),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(default='employee', max_length=50),
        ),
    ]
