# Generated by Django 5.0.5 on 2024-05-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_joining',
            field=models.DateField(blank=True, default='27-05-2024', null=True),
        ),
    ]
