# Generated by Django 5.0.5 on 2024-05-11 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_photo_employee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workschedule',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
