# Generated by Django 5.0.5 on 2024-05-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_date_join'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_join',
            field=models.DateField(blank=True, default='2024-05-11', null=True),
        ),
    ]
