# Generated by Django 5.0.5 on 2024-06-14 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0001_initial'),
        ('employees', '0005_alter_employee_date_of_joining'),
    ]

    operations = [
        migrations.AddField(
            model_name='caredetail',
            name='employee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='employee_consign_care', to='employees.employee'),
        ),
    ]
