# Generated by Django 5.0.5 on 2024-06-16 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0004_remove_consignment_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignmentdetail',
            name='package',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='package_consign', to='consignment.servicepackage'),
        ),
    ]
