# Generated by Django 5.0.5 on 2024-06-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0005_consignmentdetail_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='caredetail',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
