# Generated by Django 5.0.5 on 2024-06-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0006_caredetail_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignmentinvoice',
            name='price',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
