# Generated by Django 5.0.5 on 2024-06-17 00:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0007_alter_consignmentinvoice_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignment',
            name='date_time_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 6, 17, 0, 23, 54, 246994, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='consignmentdiary',
            name='date_time_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 6, 17, 0, 23, 54, 247856, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='consignmentinvoice',
            name='date_time_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 6, 17, 0, 23, 54, 248081, tzinfo=datetime.timezone.utc)),
        ),
    ]
